# 管理员，可以不填，不填删掉。首次启动自动设置管理员。
admin:
- 12345678

bot:
  # bot的token, 首次启动必填
  token: null

# 后端配置
slaveConfig:
  # checkslave 后端健康检查配置
  healthCheck:
    # 健康检查样本数量，单位整数次数，默认采样10次PING测试数据
    numSamples: 10
    # 在后端选择页面展示状态的样式，共有以下可用值： ["emoji", "number", "default"]，分别代表：展示emoji、展示延迟、不展示，默认default不展示
    showStatusStyle: "default"
  # 后端列表，注意是数组类型
  slaves:
    # 固定值，目前只这个支持
    - type: miaospeed
      # 后端id
      id: "localmiaospeed"
      # 连接密码
      token: "ZfffaQ4/E-7S"
      # 后端地址
      address: "127.0.0.1:8765"
      # websocket的连接路径，只有路径正确才能正确连接，请填写复杂的路径，防止路径被爆破。可以有效避免miaospeed服务被网络爬虫扫描到.
      path: "/"
      # 跳过证书验证，如果你不知道在做什么，请写此默认值
      skipCertVerify: true
      # 启用加密连接，如果你不知道在做什么，请写此默认值
      tls: true
      # bot调用者，请删掉此行或者随便填一个字符串
      invoker: "1114514"
      # 默认编译token  如果你不知道在做什么，请写此默认值
      buildtoken: "MIAOKO4|580JxAo049R|GEnERAl|1X571R930|T0kEN"
      # 后端备注，显示在bot页面的
      comment: "本地miaospeed后端"
      option:
        # 测试时长
        downloadDuration: 8
        # 测速线程
        downloadThreading: 4
        # 测速大文件，有一个特殊值：DYNAMIC:ALL，表示随机选择一个下载地址，随机选择列表需要在runtime.speedFiles里或rule.runtime.speedFiles里设置。
        downloadURL: https://dl.google.com/dl/android/studio/install/3.4.1.0/android-studio-ide-183.5522156-windows.exe
        # 延迟测试地址
        pingAddress: https://cp.cloudflare.com/generate_204
        # ping多少次取平均
        pingAverageOver: 3
        # STUN地址，测udp连通性的，格式: udp://host:port
        stunURL: udp://stunserver2025.stunprotocol.org:3478
        # 后端任务重试，单位秒(s)
        taskRetry: 3
        # 后端任务超时判定时长，单位毫秒(ms)
        taskTimeout: 2500
        # 后端指定dns服务器，解析节点域名时会用到。例子: ["119.29.29.29:53", "223.5.5.5:53"]
        dnsServer: []
        # 后端Api版本，设置为 0或者1可以适配旧版后端兼容性，默认为2，如无必要请勿修改。如果要对接其他分支miaospeed请设置为0或者1
        apiVersion: 1

# 用户权限名单，不用自己设，推荐使用 /grant 指令添加用户权限
user: []
